version: '3.8'

services:
  bot:
    image: us-central1-docker.pkg.dev/algo-trade-480920/bot-repo/ai-scalper:v6.9
    container_name: bot
    restart: always
    env_file: .env  # Всі API ключі тримаємо тут!
    volumes:
      - ./bot_data:/app/data  # Стандартизуємо шлях
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "3"

  website:
    image: us-central1-docker.pkg.dev/algo-trade-480920/bot-repo/ai-scalper:v6.9
    container_name: website
    restart: always
    ports:
      - "80:8000" # Краще відкрити стандартний 80 порт
    env_file: .env
    depends_on:
      - bot
    volumes:
      - ./bot_data:/app/data
    command: python manage.py runserver 0.0.0.0:8000