from typing import Protocol, List

class NotifierProtocol(Protocol):
    """Абстракція сервісу сповіщень (Telegram/Slack/Email)."""
    async def send_message(self, text: str) -> None:
        ...


class TradingRepositoryProtocol(Protocol):
    """Абстракція інфраструктурного шару збереження даних (SQLAlchemy/Tortoise ORM)."""
    def load_balance(self, default_balance: float) -> float: ...
    def save_balance(self, balance: float) -> None: ...
    def get_all_positions(self) -> List[image_model_placeholder]: ...  # Повертає об'єкти з БД
    def save_position(self, symbol: str, amount: float, entry_price: float, highest_price: float, cost: float) -> None: ...
    def update_position_high(self, symbol: str, highest_price: float) -> None: ...
    def delete_position(self, symbol: str) -> None: ...
    def log_trade(self, symbol: str, side: str, price: float, amount: float, cost: float, pnl: float) -> None: ...