# Generated by Django 5.2.13 on 2026-05-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivePosition",
            fields=[
                (
                    "symbol",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("amount", models.FloatField()),
                ("entry_price", models.FloatField()),
                ("highest_price", models.FloatField()),
                ("cost", models.FloatField()),
                ("opened_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Активна позиція",
                "verbose_name_plural": "Активні позиції",
                "db_table": "active_positions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("symbol", models.CharField(max_length=20)),
                ("side", models.CharField(max_length=10)),
                ("price", models.FloatField()),
                ("amount", models.FloatField()),
                ("cost", models.FloatField()),
                ("pnl", models.FloatField(default=0.0)),
                ("timestamp", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Угода",
                "verbose_name_plural": "Угоди",
                "db_table": "trades",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("usdt_balance", models.FloatField()),
            ],
            options={
                "verbose_name": "Гаманець",
                "verbose_name_plural": "Гаманці",
                "db_table": "wallet",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BotConfig",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(default="stopped", max_length=20)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Конфігурація бота",
                "db_table": "bot_config",
                "managed": True,
            },
        ),
    ]
