services:
  engine:
    build:
      context: ..
      dockerfile: infrastructure/docker/engine.Dockerfile
    container_name: algo_engine
    restart: unless-stopped
    command: python main.py
    environment:
      - PYTHONPATH=/app:/app/src  # <-- ДОДАЙТЕ ЦІ ДВА РЯДКИ
    volumes:
      - ../logs:/app/logs
      - ../data_storage:/app/data_storage
    env_file:
      - ../.env

  web_panel:
    # ... тут все залишається без змін
    build:
      context: ..
      dockerfile: infrastructure/docker/engine.Dockerfile
    container_name: algo_web
    working_dir: /app/src
    command: gunicorn web_panel.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ..:/app
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - engine
